name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Before opening a new issue, please search for the behaviour in the existing issues.
  - type: input
    id: bug-description
    attributes:
      label: Bug Description
      description: "Describe the bug"
      placeholder: "Description about the Bug"
    validations:
      required: true
  - type: textarea
    id: step-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Brief description about how to reproduce the issue
      placeholder: Visit to ....
                   Click on .... etc
    validations:
      required: true
  - type: textarea
    id: attachement-url
    attributes:
      label: Attachment or URL
      description: Please attach a screenshoot here or paste a URL
    validations:
      required: true
  - type: input
    id: Expected_behaviour
    attributes:
      label: Expected Result
      description: "Expected behavior"
      placeholder: "Expected behavior"
    validations:
      required: true
  - type: input
    id: actualresult
    attributes:
      label: Actual Result
      description: "Actual behavior"
      placeholder: "Actual behavior"
    validations:
      required: true
  - type: dropdown
    id: urgency
    attributes:
      label: How urgently is the fix required
      description: Please choose how urgently is this fix required?
      options:
        - Very Urgent (Need fix in single day)
        - Urgent (Need fix within a week or two)
        - Not urgent (Fix within a month or more)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: dropdown
    id: Priority
    attributes:
      label: What's the priority of this issue'?
      multiple: true
      options:
        - Critical
        - High
        - Medium
        - Low
  - type: checkboxes
    id: reported_by
    attributes:
      label: Reported By
      description: Who Reported this Bug
      options:
        - label: Customer
        - label: Sales
        - label: Customer Support/Success
        - label: Internal Stakeholder
        - label: Internal - DX Team/QA

    
